In [10]:
import torch
import torch.nn as nn

x = torch.Tensor([[[[1]]]])
# 定义四个方向的补零数量
zero_pad = nn.ZeroPad2d(padding=(1, 2, 3, 4))
y = zero_pad(x)
print(y)

# 输出结果：
# tensor([[[[0., 0., 0., 0.],
#           [0., 0., 0., 0.],
#           [0., 0., 0., 0.],
#           [0., 1., 0., 0.],
#           [0., 0., 0., 0.],
#           [0., 0., 0., 0.],
#           [0., 0., 0., 0.],
#           [0., 0., 0., 0.]]]])

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [12]:
# 设定边界填充为常量值19
const_pad = nn.ConstantPad2d(padding=(1, 2, 3, 4), value=19)
y = const_pad(x)
print(y)

# 输出结果：
# tensor([[[[19., 19., 19., 19.],
#           [19., 19., 19., 19.],
#           [19., 19., 19., 19.],
#           [19.,  1., 19., 19.],
#           [19., 19., 19., 19.],
#           [19., 19., 19., 19.],
#           [19., 19., 19., 19.],
#           [19., 19., 19., 19.]]]])

tensor([[[[19., 19., 19., 19.],
          [19., 19., 19., 19.],
          [19., 19., 19., 19.],
          [19.,  1., 19., 19.],
          [19., 19., 19., 19.],
          [19., 19., 19., 19.],
          [19., 19., 19., 19.],
          [19., 19., 19., 19.]]]])
