In [9]:
import torch
import torch.nn as nn

class miniConv(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(1, 1, 1)

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(1, 1, 1)
        self.mini = miniConv()
      
    def forward(self):
        return 0

('conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
('mini', miniConv(
  (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
))


In [14]:
net = Net()
for param in net.named_parameters():
    print(param)
# 输出结果：
# ('conv.weight', Parameter containing:
# tensor([[[[-0.8251]]]], requires_grad=True))
# ('conv.bias', Parameter containing:
# tensor([0.7367], requires_grad=True))
# ('mini.conv.weight', Parameter containing:
# tensor([[[[-0.1005]]]], requires_grad=True))
# ('mini.conv.bias', Parameter containing:
# tensor([0.7705], requires_grad=True))

('conv.weight', Parameter containing:
tensor([[[[-0.8251]]]], requires_grad=True))
('conv.bias', Parameter containing:
tensor([0.7367], requires_grad=True))
('mini.conv.weight', Parameter containing:
tensor([[[[-0.1005]]]], requires_grad=True))
('mini.conv.bias', Parameter containing:
tensor([0.7705], requires_grad=True))


In [15]:
for child in net.named_children():
    print(child)
# 输出结果：
# ('conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
# ('mini', miniConv(
#   (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
# ))

('conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
('mini', miniConv(
  (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
))


In [16]:
for module in net.named_modules():
    print(module)
# 输出结果：
# ('', Net(
#   (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
#   (mini): miniConv(
#     (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
#   )
# ))
# ('conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
# ('mini', miniConv(
#   (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
# ))
# ('mini.conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))

('', Net(
  (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
  (mini): miniConv(
    (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
  )
))
('conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
('mini', miniConv(
  (conv): Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1))
))
('mini.conv', Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1)))
