In [1]:
# 下面代码讲述的是Tensor的操作
import torch
x = torch.tensor([1, 2, 3, 4, 5])
print(x[1:3])
# tensor([2, 3])

print(x[:])

tensor([2, 3])
tensor([1, 2, 3, 4, 5])


In [2]:
import torch
x = torch.tensor([1, 2])
y = torch.tensor([1, 2])
# 通过克隆y获得z
z = y.clone()
# 将y从计算图中分离
q = y.detach()
print(x.data_ptr())
print(y.data_ptr())
print(z.data_ptr())
print(q.data_ptr())
# 输出结果：
# 1772260424512
# 1772260423424
# 1772260424384
# 1772260423424

2640887649728
2640887649024
2640887645696
2640887649024


In [ ]:
import torch
x = torch.tensor([1, 2, 3, 4, 5])
# 获取区间1到3内的数值
print(x[1:3])
# 获取全部数值
print(x[:])
# 获取最后一个数值
print(x[-1])

# 输出结果
# tensor([2, 3])
# tensor([1, 2, 3, 4, 5])
# tensor(5)

In [3]:
x1 = torch.tensor([1, 2])
x2 = torch.tensor([3, 4])
x3 = torch.tensor([5, 6])

x_cat = torch.cat(tensors=(x1, x2, x3), dim=0)
print(x_cat)
# 输出：tensor([1, 2, 3, 4, 5, 6])

tensor([1, 2, 3, 4, 5, 6])


In [4]:
x1 = torch.tensor([[1, 2], [3, 4]])
x2 = torch.tensor([[1, 2], [3, 4]])
print(torch.mul(x1, x2))
print(torch.mm(x1, x2))
# tensor([[ 1,  4],
#         [ 9, 16]])
# tensor([[ 7, 10],
#         [15, 22]])

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


In [5]:
x1 = torch.tensor([[1, 2], [3, 4]])
x2 = torch.tensor([[1, 2], [3, 4]])
print(torch.add(x1, x2))
print(torch.sub(x1, x2))
# tensor([[2, 4],
#         [6, 8]])
# tensor([[0, 0],
#         [0, 0]])

print(x1.add_(x2))
x1 = torch.tensor([[1, 2], [3, 4]])
print(x1.sub_(x2))
# tensor([[2, 4],
#         [6, 8]])
# tensor([[0, 0],
#         [0, 0]])

tensor([[2, 4],
        [6, 8]])
tensor([[0, 0],
        [0, 0]])
tensor([[2, 4],
        [6, 8]])
tensor([[0, 0],
        [0, 0]])
