In [1]:
# 下面是介绍retain_graph
import torch

x = torch.randn((1, 3), requires_grad=True)
y = x.sum()
z = 2 * y

z.backward(retain_graph=True)
print(x.grad)
# RuntimeError: Trying to backward through the graph a second time,
# but the buffers have already been freed. 
# Specify retain_graph=True when calling backward the first time.
z.backward()
print(x.grad)

tensor([[2., 2., 2.]])
tensor([[4., 4., 4.]])


In [2]:
z.backward(retain_graph=True)
print(x.grad)
z.backward()
print(x.grad)
# 输出结果：
# tensor([[2., 2., 2.]])
# tensor([[4., 4., 4.]])

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.