In [1]:
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self, nc):
        super().__init__()
        self.bn = nn.BatchNorm2d(nc, affine=True)
    
    def forward(self, x):
        return self.bn(x)

nc = 1
total_iterations = 2
net = Net(nc)
net.train()
x = torch.randn(1, nc, 2, 2)
for i in range(total_iterations):
    
    pred = net(x)
#     print(net.bn.weight, net.bn.bias)
#     for param in net.bn.named_parameters():
#         print(param)
    print(pred)

tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4479,  0.4114],
          [-0.9837, -0.8756]]]], grad_fn=<NativeBatchNormBackward>)


In [2]:
net.eval()
# x = torch.randn(1, nc, 2, 2)
for i in range(total_iterations):
    pred = net(x)
#     print(net.bn.weight, net.bn.bias)
#     for param in net.bn.named_parameters():
#         print(param)
    print(pred)

tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)
tensor([[[[ 1.4227,  0.4796],
          [-0.7899, -0.6915]]]], grad_fn=<NativeBatchNormBackward>)


In [5]:
bn = nn.BatchNorm2d(3)
print(dir(bn))
print(bn.running_mean)
print(bn.running_var)

['__call__', '__class__', '__constants__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_backward_hooks', '_buffers', '_check_input_dim', '_forward_hooks', '_forward_pre_hooks', '_get_name', '_load_from_state_dict', '_load_state_dict_pre_hooks', '_modules', '_named_members', '_parameters', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_replicate_for_data_parallel', '_save_to_state_dict', '_slow_forward', '_state_dict_hooks', '_version', 'add_module', 'affine', 'apply', 'bfloat16', 'bias', 'buffers', 'children', 'cpu', 'cuda', 'double', 'dump_patches', 'eps', 'eval', 'extra_repr', 'float', 'forward', 'half', 'load_state_dict', 'modules', 'mome

In [ ]:
import torch
import torch.nn as nn

# 定义一个只包含BN层的网络
class Net(nn.Module):
    def __init__(self, nc):
        super().__init__()
        # 定义BN层，指定BN的输入通道数
        self.bn = nn.BatchNorm2d(nc, affine=True)
    
    def forward(self, x):
        return self.bn(x)

# 通道数设定为2
nc = 2
net = Net(nc)

# 将网络设定为训练模式
net.train()
for i in range(5):
    x = torch.randn(1, nc, 2, 2)
    _ = net(x)
    # 打印网络bn层计算的均值和方差信息
    print("mean: ", net.bn.running_mean.data)
    print("var: ", net.bn.running_var.data)

# 输出结果:
# mean:  tensor([ 0.0888, -0.0052])
# var:  tensor([1.0771, 0.9486])
# mean:  tensor([ 0.0584, -0.0013])
# var:  tensor([1.1610, 0.9938])
# mean:  tensor([-0.0395, -0.0017])
# var:  tensor([1.1344, 0.9531])
# mean:  tensor([-0.0130,  0.0616])
# var:  tensor([1.1179, 0.9074])
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])

# 将网络设定为评估模式
net.eval()
for i in range(5):
    x = torch.randn(1, nc, 2, 2)
    _ = net(x)
    print("mean: ", net.bn.running_mean.data)
    print("var: ", net.bn.running_var.data)
# 输出结果:
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])
# mean:  tensor([ 0.0168, -0.0400])
# var:  tensor([1.0957, 0.8489])

In [ ]:
net.train()
for i in range(1000000):
    x = torch.randn(1, nc, 2, 2)
    _ = net(x)
    if i % 100000 == 0:
        print(net.bn.running_mean.data)
        print(net.bn.running_var.data)

In [ ]:
net = nn.Linear(1, 1)
net.train()
net.eval()