In [1]:
# 下面代码讲述的是Tensor的创建

import torch

x1 = [1, 2, 3]
x1_tensor = torch.tensor(x1, dtype=torch.int32)
print(x1_tensor)
# tensor([1, 2, 3], dtype=torch.int32)



tensor([1, 2, 3], dtype=torch.int32)


In [2]:
import numpy as np

x2_numpy = np.array([1, 2, 3])
x2_tensor = torch.from_numpy(x2_numpy)
print(x2_tensor)
# 输出：tensor([1, 2, 3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)


In [3]:
x3_tensor = torch.ones_like(x2_tensor)
print(x3_tensor)
# 输出：tensor([1, 1, 1], dtype=torch.int32)

tensor([1, 1, 1], dtype=torch.int32)


In [4]:
size = [1, 3]
x4_tensor = torch.randn(size)
x5_tensor = torch.zeros(size)
print(x4_tensor)
print(x5_tensor)
# tensor([[0.9306, 0.3131, 0.5407]])
# tensor([[0., 0., 0.]])

tensor([[ 0.5698, -0.3418, -0.1891]])
tensor([[0., 0., 0.]])


In [5]:
# # 下面代码分析的是Tensor的属性

# x = torch.randn(size=(1, 2))
# print("Tensor size: {}".format(x.size()))
# print("Tensor device: {}".format(x.device))
# print("Tensor data type: {}".format(x.dtype))
# # Tensor size: torch.Size([1, 2])
# # Tensor data type: torch.float32
# # Tensor device: cpu

Tensor size: torch.Size([1, 2])
Tensor device: cpu
Tensor data type: torch.float32
