In [1]:
# 下面是Tensor维度信息
import torch

x = torch.randn(1, 3, 4, 4)
print("ndimension: ", x.ndimension())
print("nelement: ", x.nelement())
print("size: ", x.size())
print("shape: ", x.shape)
# 输出结果
# ndimension:  4
# nelement:  48
# size:  torch.Size([1, 3, 4, 4])
# shape:  torch.Size([1, 3, 4, 4])

ndimension:  4
nelement:  48
size:  torch.Size([1, 3, 4, 4])
shape:  torch.Size([1, 3, 4, 4])


In [2]:
x_view = x.view(1, 3, 4 * 4)
print("x_view: ", x_view.size())
x_view = x.view(1, -1)
print("x_view: ", x_view.size())
# 输出结果
# x_view:  torch.Size([1, 3, 16])
# x_view:  torch.Size([1, 48])

x_view:  torch.Size([1, 3, 16])
x_view:  torch.Size([1, 48])


In [3]:
x = torch.randn(2, 3)
print(x)
x_trans = x.transpose(1, 0)
print(x_trans)
# 输出结果：
# tensor([[-0.6668,  0.2579, -0.9531],
#         [-0.3596,  1.0273, -0.9150]])
# tensor([[-0.6668, -0.3596],
#         [ 0.2579,  1.0273],
#         [-0.9531, -0.9150]])

tensor([[-0.8167,  1.1508,  1.3100],
        [ 1.2471,  0.4875, -0.2938]])
tensor([[-0.8167,  1.2471],
        [ 1.1508,  0.4875],
        [ 1.3100, -0.2938]])


In [4]:
# 增加和删除维度
x = torch.randn(1, 3, 16, 16)
x = x.squeeze(0)
print(x.size())
x = x.unsqueeze(0)
print(x.size())
# 输出结果
# torch.Size([3, 16, 16])
# torch.Size([1, 3, 16, 16])

torch.Size([3, 16, 16])
torch.Size([1, 3, 16, 16])
